---
# Worker Node Setup
- hosts: worker_nodes
  become: true
  tasks:
    - name: Join Kubernetes cluster
      shell: |
        kubeadm join {{ hostvars['global'].resolved_control_plane_ip }}:6443 --token {{ hostvars['control_node'].kube_token }} --discovery-token-ca-cert-hash sha256:{{ hostvars['control_node'].cert_hash }} --cri-socket unix:///var/run/cri-dockerd.sock --v=5
      args:
        creates: /var/lib/kubelet/kubeadm-flags.env
      become: true
    - name: Ensure .kube directory exists
      file:
        path: "~{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
      become_user: "{{ ansible_user }}"  # Ensure directory is created under the correct user
    - name: Display ansible_user
      debug:
        msg: "ansible_user is {{ ansible_user }}"